baseURL                    = "https://peter-xs.github.io/"
languageCode               = "zn-Hans"
title                      = "PeterX | Blogs"
builddrafts                = false
canonifyurls               = true
contentdir                 = "content"
layoutdir                  = "layouts"
publishdir                 = "public"
enableEmoji                = true
hasCJKLanguage             = true
summaryLength              = 200
Paginate                   = 3

pygmentsuseclasses         = true


[permalinks]
  blog                     = "blog/:year-:month/:slug/"


[taxonomies]
  tag                      = "tags"
  series                   = "series"
  category                 = "categories"

[menu]
  [[menu.main]]
    name                   = "Blog"
    weight                 = -120
    identifier             = "blog"
    url                    = "blog/"  

  [[menu.main]]
    name                   = "Moment"
    weight                 = -110
    identifier             = "moment"
    url                    = "moment/" 

  [[menu.main]]
    name                   = "About"
    weight                 = -100
    identifier             = "about"
    url                    = "about/"  

[params]
  faviconfile              = "img/avatar-sm.jpg"               # from static/
  avatar                   = "img/avatar.jpg"             # path to image in static dir e.g img/avatar.png 
  author                   = "PeterX"
  description              = ["Enjoy your life.", "Enjoy your trips."]           # appears in the site header when set to a non-empty string
  welcome_head             = "Hello, World!"
  welcome_word             = "Let's do something meaningful"

  latestpostscount         = 5                             # how many posts to display on the home page
  bloggroupby              = 'month'
  dateform                 = "Jan 2, 2019"
  dateformfull             = "2019-01-02  Monday  15:04:05"
  noshowreadtime           = true                         # if true, don't show "<x> minutes read" in posts

  # slides
  slidesDirPath            = "static/img/header-slides"    # path to image in local dir (path for hugo)
  slidesDirPathURL         = "img/header-slides"    # path to image in static dir (for static pages)

  # highlighting 
  highlightjs              = true

  # latex
  katex                    = true

  # links
  email                    = "you@email.com"
  github                   = "//github.com/peter-xs"
  linkedin                 = "//linkedin.com/in/you"
  facebook                 = "//facebook.com/you"
  googleplus               = "//google.com/you"
  twitter                  = "//twitter.com/you" 
  px500                    = "//px500"
  instagram                = "//instagram.com/you"
  include_rss              = false                          # include RSS <link> tag in <head> and show RSS icon
  
  # analytics
  googleAnalytics          = "your-google-analytic-id"
    
    